name: Gerar App Android (APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Motor Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false
        
    - name: Preparar Mutacao do Pacote Go
      working-directory: ./lab_go
      run: |
        mkdir -p mobile
        cp main.go mobile/mobile.go
        cp -r static mobile/ || true
        cp -r templates_teste mobile/ || true
        cp equipamentos.json mobile/ || true
        sed -i 's/package main/package mobile/g' mobile/mobile.go
        sed -i 's/func main()/func StartServer()/g' mobile/mobile.go
        cd mobile
        go mod init mobile
        
    - name: Instalar Ferramentas Android e Go
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        export PATH=$PATH:$(go env GOPATH)/bin
        gomobile init
        
    - name: Compilar Motor Offline (.aar)
      working-directory: ./lab_go/mobile
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get golang.org/x/mobile/bind
        mkdir -p ../android/app/libs
        gomobile bind -target=android -androidapi 21 -o ../android/app/libs/Mobile.aar .
        
    - name: Gerar App Android
      working-directory: ./lab_go/android
      run: gradle assembleDebug
        
    - name: Guardar Instalador Final
      uses: actions/upload-artifact@v4
      with:
        name: Instalador-Android-APK
        path: lab_go/android/app/build/outputs/apk/debug/app-debug.apk
